---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: client-secrets
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_AZUREAD_CLIENT_SECRET: AgApCc4BScRAGujB8GL3mafvldf+beptCLsRnwxtQyUjTrK8ZLP704Vcqt280RwFBEs5lAJ1UQ+zUxa/+ukqDzaphdO7XOWmlgpEcvXDmRrSz0ECeKwSFfJTvRt3L9Qx4GxbZvVbnRNXR9kS96GrwnEgh+hfbGskKmVsjoc92Lex74wZ0Bro1RcMpQS6PPzX8HCTRPzPlh/pTVg037tDnygrsJcFLSk9E/1SA1yrWPZ1cJOU4LtdQfvboZfkKxwLSlnmWClEKMBnxGaEzFUoOtuziOyxS7wXY6ZtJD/yYalpEZj+S4m/spmNxNcwPNC77MuBCU+Whp28JvdlSyZKBn2h5f1wi/iPPiZb04E0W/DXCStnjCKLvqWrexYlU4Qm5BSk+dhU4nekOxPkKqIKqJ0OGAUnBa0AjnqDOsI4NxQjmTx6L4BmJRzmQ9iA3ODsXjYWyfgTJnM5vmVyl26EgSsha9+LbOWCUgDT8GagqQrvRU1ukjaL61dwJF/pzOosaXIOwQ9B5nXOMGqDH29Qq1QTzC6Pw9quB1pqOSn0+zev3ICpeEadzYBFW8633ApLSKTkj8jYJ5/ag2DpFHUQkOUEVmxNMTRJD+ZIueJ0HizzSa02fBIMZ+8xHCmtCjJ0O4k7jcNa14GDA1Sj+ZjIqFbx8NPtx/n7GikEwpQZoP9/OuaSft/KgDB/Mrq2+9MR+OXf0aTiUvvyKDjvLDYoboujVuumTlIJvQKPU9uczkZwev4XIUvEOSOy
  template:
    metadata:
      creationTimestamp: null
      name: client-secrets
      namespace: monitoring
    type: Opaque
