---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-admin-creds
  namespace: backstage
spec:
  encryptedData:
    password: AgCau/QPdICZGUY8imvGL/EFOjEhLDEPNyKJNdLBvf6nKlJNjX3dOCvvMogvvYclGSp3Ffna6cuEasCl814wgltKit59wQAXyOUlAu5hBhumCANIqZGBCLATCnWC8u1j429UmCvvvV0x3bX1OE1tkbkZ+TpTe4m989+F4269/l1h0qiZCT+hhdZhC81RrU8LyIflNkVXNtPDaeSvYvHrw0k9UW/2OvOTOFrd1yECr9WF0JtkENikEW8i9YOiU3XMZ60k7bMnWF68mWlmrPM0G4S8Zsv0Vdm9HuSenIo92JnHhFeWpcwyJoYB8wh1jMbED774qfFg9gSlK3bsbYHVemQm8hDxsYqEUiJxlV3njbP+KzPyjE/NLkLCchvqilzoNb5b+1sVVmpZ+NHSbs348X19uMztIqn6JybgY2bg5KFRIjKfGoY3idKKr1B2yoBs5+nKr5dTTabvhoRyGAADrdDiKysMX84ZOLQu4RGnz2BW5cE9FO63Gn6si6zzqhwfhkAYnnKnXSijkmrL90MezXymvZSwm49iE9Zxu+c/r+HU+6JTvVSDn9+WOjVMZ8ffloR8lYQGo1sPnJgqitBISkNJMUUiCieboH1iRT1V0EiMKE3oISP2p9vG8DUfAWmVpHXfP2vHZFy6HXSF5dwCdofb7GSHjjpgMdvLNJj64iJeQngOw/GV4+951ywxFJ5ADUDh8sfRYMmk94Q=
  template:
    metadata:
      name: db-admin-creds
      namespace: backstage
    type: Opaque
