apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: ingress-nginx
spec:
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: false
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
      - Replace=false
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.*
    helm:
      releaseName: ingress-nginx
      passCredentials: false
      parameters:
        - name: "controller.metrics.enabled"
          value: "true"
        - name: "controller.metrics.serviceMonitor.enabled"
          value: "true"
        - name: "controller.metrics.serviceMonitor.additionalLabels.release"
          value: "monitoring"
        - name: "controller.podAnnotations.prometheus\\.io/scrape"
          value: "true"
          forceString: true # ensures that value is treated as a string 
        - name: "controller.podAnnotations.prometheus\\.io/port"
          value: "10254"
          forceString: true # ensures that value is treated as a string 
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingress-nginx
  revisionHistoryLimit: 3

